version: '3.8'

services:
  parser:
    container_name: parser
    build:
      context: .
    volumes:
      - ./cron:/etc/cron.d/crontab
    restart: always
    env_file: .env
    network_mode: host
